name: Build artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: "install dependencies"
        run: npm ci

      - name: full build and deploy
        run: npm run deploy

      - name: Get package version, write to .env file
        run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Log version in js file
        run: echo "//script.name=AdvancedOperator v${{ env.VERSION }} by IR0NSIGHT" | cat - dist/AdvancedOperator/AdvancedOperator.js > temp && mv temp dist/AdvancedOperator/AdvancedOperator.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AdvancedOperator_v${{ env.VERSION }}
          path: dist/AdvancedOperator
