name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Verify Node.js and NPM installation
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: log runner
        run: id; whoami

      - name: "install dependencies"
        run: npm install

      - name: full build and deploy
        run: npm run deploy

      - name: debug - check built file
        run: ls -R dist ;cat dist/AdvancedOperator/AdvancedOperator.js

      - name: Get package version, write to .env file
        run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Log version in js file
        run: echo "//script.name=AdvancedOperator v${{ env.VERSION }} by IR0NSIGHT" | cat - dist/AdvancedOperator/AdvancedOperator.js > temp && mv temp dist/AdvancedOperator/AdvancedOperator.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AdvancedOperator_v${{ env.VERSION }}
          path: dist/AdvancedOperator
